steps:
- name: node:18.17.0
  entrypoint: npm
  args: ["install", "--force"]
- name: node:18.17.0
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"